  # /********************************************************************************
# * Copyright (c) 2024 Leonardo Rossetti <lrossett@redhat.com>
# * Portions Copyright (c) Microsoft Corporation.
# *
# * This program and the accompanying materials are made available under the 2
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0.txt.
# *
# * SPDX-License-Identifier: Apache-2.0
# *
# * Contributors: 1
# *   Leonardo Rossetti - file creation
# ********************************************************************************/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agemo
  name: agemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agemo
  template:
    metadata:
      labels:
        app: agemo
    spec:
      hostNetwork: true
      containers:
        - name: pub-sub-service
          image: ghcr.io/eclipse-sdv-blueprints/software-orchestration/eclipse-agemo/pub-sub-service:0.1.2
          imagePullPolicy: IfNotPresent
