# /********************************************************************************
# * Copyright (c) 2024 Leonardo Rossetti <lrossett@redhat.com>
# *
# * This program and the accompanying materials are made available under the 2
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0.txt.
# *
# * SPDX-License-Identifier: Apache-2.0
# *
# * Contributors: 1
# *   Leonardo Rossetti - file creation
# ********************************************************************************/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chariott
  name: chariott
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chariott
  template:
    metadata:
      labels:
        app: chariott
    spec:
      hostNetwork: true
      containers:
        - name: service-discovery
          image: ghcr.io/eclipse-sdv-blueprints/software-orchestration/eclipse-chariott/service-discovery:0.2.1
          imagePullPolicy: IfNotPresent
