# /********************************************************************************
# * Copyright (c) 2024 Leonardo Rossetti <lrossett@redhat.com>
# *
# * This program and the accompanying materials are made available under the 2
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0.txt.
# *
# * SPDX-License-Identifier: Apache-2.0
# *
# * Contributors: 1
# *   Leonardo Rossetti - file creation
# ********************************************************************************/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: freyja
  name: freyja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freyja
  template:
    metadata:
      labels:
        app: freyja
    spec:
      hostNetwork: true
      containers:
        - name: local-cloud-sync
          image: ghcr.io/ladatz/sdvblueprint/eclipse-freyja/local-with-ibeji:0.1.0
          imagePullPolicy: IfNotPresent
