name: Containerize Chariott

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Chariott
        uses: actions/checkout@v2
        with:
          repository: eclipse-chariott/chariott

      - name: Build and push multi-platform Docker image for Chariott Service Discovery
        uses: docker/build-push-action@v2
        with:
            context: .
            file: Dockerfile.service_discovery.multi
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ghcr.io/ladatz/software-orchestration/eclipse-chariott/service-discovery:0.2.0

      - name: Make Image Public
        run: |
          curl -X PUT \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"visibility": "public"}' \
          "https://api.github.com/repos/ladatz/software-orchestration/packages/container/eclipse-chariott/service-discovery/visibility"
