# SPDX-License-Identifier: MIT

name: Containerize In-Vehicle Stack - Ibeji

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Ibeji
        uses: actions/checkout@v2
        with:
          repository: eclipse-ibeji/ibeji
          ref: 0.1.1
          submodules: recursive

      - name: Build and push multi-platform Docker image for Ibeji In-vehicle Digital Twin
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_integrated.multi
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/eclipse-sdv-blueprints/software-orchestration/eclipse-ibeji/invehicle-digital-twin:0.1.1
