# Copyright (c) Microsoft Corporation.
# Licensed under the Apache License, Version 2.0.
# SPDX-License-Identifier: Apache-2.0

name: Containerize Sample Workloads - Smart Trailer

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build and push multi-platform Docker image for the Trailer Properties Provider
        uses: docker/build-push-action@v5
        with:
          context: ./scenarios/smart_trailer
          file: ./scenarios/smart_trailer/Dockerfile.sample_workloads
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/eclipse-sdv-blueprints/software-orchestration/invehicle-stack/trailer-properties-provider:0.1.0

      - name: Build and push multi-platform Docker image for the Trailer Connected Provider
        uses: docker/build-push-action@v5
        with:
          context: ./scenarios/smart_trailer
          file: ./scenarios/smart_trailer/Dockerfile.sample_workloads
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/eclipse-sdv-blueprints/software-orchestration/invehicle-stack/trailer-connected-provider:0.1.0
          build-args: |
            APP_NAME=trailer_connected_provider

      - name: Build and push multi-platform Docker image for the Smart Trailer Application
        uses: docker/build-push-action@v5
        with:
          context: ./scenarios/smart_trailer
          file: ./scenarios/smart_trailer/Dockerfile.sample_workloads
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/eclipse-sdv-blueprints/software-orchestration/invehicle-stack/smart-trailer-application:0.1.0
          build-args: |
            APP_NAME=smart_trailer_application
      
