# SPDX-License-Identifier: MIT
name: Containerize In-Vehicle Stack - Freyja Apps

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Freyja Apps Repository
        uses: actions/checkout@v2
        with:
          repository: eclipse-ibeji/ibeji-example-applications
          ref: 0.1.0
          submodules: recursive

      - name: Build and push multi-platform Docker image for Freyja Application
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.freyja_apps.multi
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/ladatz/software-orchestration/eclipse-freyja/local-with-ibeji:0.1.0
          build-args: |
            APP_NAME=freyja-ibeji-integration-app
            CONFIG_PATH=.freyja/smart_trailer/config
